name: Botonic Examples - Tests

on: [push]

jobs:
  botonic-examples-tests:
    name: Examples tests
    runs-on: ubuntu-latest
    steps:
      - name: Checking out to current branch
        uses: actions/checkout@v1
      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Setting up cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: blank build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: blank
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: blank-typescript build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: blank-typescript
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: childs build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: childs
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: custom-webchat build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: custom-webchat
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: dynamic-carousel build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: dynamic-carousel
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: dynamodb build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: dynamodb
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: handoff build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: handoff
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: intent build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: intent
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: nlu build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: nlu
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
      - name: tutorial build & test
        env:
          BOTONIC_DISABLE_MIXPANEL: 1
          TEST_PATH: tutorial
        run: (cd $TEST_PATH && npm install -D && npm run build && npm run test)
